export const pageMap = {
    top: "/",
    ecommerce: "/ecommerce",
    orders: "/orders",
    employees: "/employees",
    customers: "customers",
    kanban: "/kanban",
    editor: "/editor",
    calendar: "/calendar",
    colorPicker: "/color-picker",
    line: "/line",
    area: "/area",
    bar: "/bar",
    pie: "/pie",
    financial: "/financial",
    colorMapping: "/color-mapping",
    pyramid: "/pyramid",
    stacked: "/stacked",
}